### ISSUE TITLE
求分享慕课网日志数据集文件

### ISSUE THREAD

**Issue by JianWenJun** [lemonahit/LogAnalysis#1]
您好，可以分享一下该项目的慕课网日志文件吗，1343483119@qq.com，谢谢~

**Comment by lemonahit** [comment]
已将数据集的网盘地址发送至你的邮箱，请查收

- access.log为项目中进行统计分析的数据

- access.20161111.log.gz为当天的完整数据

**Comment by Cofecit** [comment]
同求这份日志数据，2234279658@qq.com，非常感谢~ @lemonahit

**Comment by lx981121263** [comment]
同求这份日志数据，981121263@qq.com，非常感谢~ @lemonahit

**Comment by new9xgh** [comment]
同求这份日志数据，244013304@qq.com，非常感谢~ @lemonahit

**Comment by lemonahit** [comment]
@Cofecit @lx981121263 @new9xgh 
日志数据的网盘地址：https://pan.baidu.com/s/19KRj1Td_aXff9WZ0Ps694g
